export const GET_USER_INFO = 'GET_USER_INFO';

export const GET_COURSE_PROGRESS = 'GET_COURSE_PROGRESS';
export const UPDATE_COURSE_PROGRESS = 'UPDATE_COURSE_PROGRESS';

export const GET_PACKAGE = 'GET_PACKAGE';
export const UPDATE_PACKAGE = 'UPDATE_PACKAGE';
